name: CI

on:
  push:
    branches:
      - main
      - master
      - refs/heads/* # Trigger for all branches
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install CMake
      run: sudo apt-get update && sudo apt-get install -y cmake

    - name: Set GTest Root
      run: echo "export GTEST_ROOT=googletest" >> $GITHUB_ENV

    - name: Configure
      run: cmake .

    - name: Build with CMake
      run: cmake --build . --config Release

    - name: Run tests
      run: ctest -C Release --output-on-failure
