name: CI

on:
  push:
    branches:
      - main
      - master
      - 'refs/heads/*' # Trigger for all branches
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Install CMake
      run: sudo apt-get update && sudo apt-get install -y cmake

    - name: Configure
      run: cmake ..
    
    - name: Build with CMake
      run: cmake --build . --config Release

    - name: Run tests
      run: ctest -C Release --output-on-failure

