name: CI

on:
  push:
    branches:
      - main
      - master
      - 'refs/heads/*' # Trigger for all branches
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up CMake
      uses: martinlindhe/cmake-action@v1

    - name: Build with CMake
      run: cmake --build . --config Release

    - name: Run tests
      run: ctest -C Release --output-on-failure

